site_name: Czuła Psychologia
site_url: https://czula.com
nav:
  - Grupa wsparcia: grupa-wsparcia.md
theme:
  name: material
  palette:
    primary: brown
  language: pl
  features:
    - navigation.footer  
plugins: 
  - blog:
      blog_dir: .
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/czula_psychologia
